"""create all tables

Revision ID: 21a72796b13e
Revises: 
Create Date: 2026-03-30 21:27:40.263223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21a72796b13e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('user_type', sa.Enum('normal', 'risk', 'diabetes', name='usertype'), nullable=False),
    sa.Column('goal', sa.Enum('diet', 'maintain', 'fitness', name='goaltype'), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'mid', 'high', name='risklevel'), nullable=True),
    sa.Column('diabetes_type', sa.Enum('type1', 'type2', name='diabetestype'), nullable=True),
    sa.Column('is_hypertension', sa.Boolean(), nullable=True),
    sa.Column('is_cholesterol', sa.Boolean(), nullable=True),
    sa.Column('is_heart_disease', sa.Boolean(), nullable=True),
    sa.Column('walking_difficulty', sa.Boolean(), nullable=True),
    sa.Column('general_health', sa.Integer(), nullable=True),
    sa.Column('alcohol_status', sa.Boolean(), nullable=True),
    sa.Column('smoke_status', sa.Boolean(), nullable=True),
    sa.Column('exercise_freq', sa.Integer(), nullable=True),
    sa.Column('fruit_intake', sa.Boolean(), nullable=True),
    sa.Column('veggie_intake', sa.Boolean(), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('target_unit', sa.String(length=20), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Enum('all', 'normal', 'risk', 'diabetes', name='challengegrade'), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'normal', 'hard', name='difficulttype'), nullable=False),
    sa.Column('challenge_type', sa.Enum('accumulate', 'toggle', name='challengetype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('completion_rate', sa.Float(), nullable=True),
    sa.Column('redesign_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_id'), 'challenges', ['id'], unique=False)
    op.create_index(op.f('ix_challenges_user_id'), 'challenges', ['user_id'], unique=False)
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('char_img_url', sa.String(length=500), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('exp', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('happy', 'normal', 'sad', 'sick', name='characterstatus'), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('stability', sa.Integer(), nullable=True),
    sa.Column('recovery', sa.Integer(), nullable=True),
    sa.Column('growth', sa.Integer(), nullable=True),
    sa.Column('last_message', sa.String(length=255), nullable=True),
    sa.Column('last_login_streak', sa.Integer(), nullable=True),
    sa.Column('last_visited_at', sa.DateTime(), nullable=True),
    sa.Column('is_graduated', sa.Boolean(), nullable=True),
    sa.Column('graduated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_characters_id'), 'characters', ['id'], unique=False)
    op.create_table('diabetes_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('top_factors', sa.String(length=500), nullable=True),
    sa.Column('is_improved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diabetes_predictions_id'), 'diabetes_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_diabetes_predictions_user_id'), 'diabetes_predictions', ['user_id'], unique=False)
    op.create_table('diet_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('carbs', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('sugar', sa.Float(), nullable=True),
    sa.Column('fiber', sa.Float(), nullable=True),
    sa.Column('gi_index', sa.Integer(), nullable=True),
    sa.Column('diet_score', sa.Integer(), nullable=True),
    sa.Column('highlight', sa.Enum('calories', 'protein', 'carbs', name='highlighttype'), nullable=True),
    sa.Column('challenge_achieved', sa.Boolean(), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diet_logs_id'), 'diet_logs', ['id'], unique=False)
    op.create_index(op.f('ix_diet_logs_user_id'), 'diet_logs', ['user_id'], unique=False)
    op.create_table('glucose_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('glucose_level', sa.Float(), nullable=False),
    sa.Column('glucose_type', sa.Enum('fasting', 'postprandial', name='glucosetype'), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glucose_logs_id'), 'glucose_logs', ['id'], unique=False)
    op.create_index(op.f('ix_glucose_logs_user_id'), 'glucose_logs', ['user_id'], unique=False)
    op.create_table('health_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('water_intake', sa.Float(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_records_id'), 'health_records', ['id'], unique=False)
    op.create_index(op.f('ix_health_records_user_id'), 'health_records', ['user_id'], unique=False)
    op.create_table('point_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_history_id'), 'point_history', ['id'], unique=False)
    op.create_index(op.f('ix_point_history_user_id'), 'point_history', ['user_id'], unique=False)
    op.create_table('points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('this_week_earned', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_points_id'), 'points', ['id'], unique=False)
    op.create_table('challenge_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('streak_count', sa.Integer(), nullable=True),
    sa.Column('fail_reason', sa.Enum('tired', 'no_time', 'weather', 'other', name='failreason'), nullable=True),
    sa.Column('execution_time', sa.Enum('morning', 'afternoon', 'evening', name='executiontime'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_logs_challenge_id'), 'challenge_logs', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_challenge_logs_id'), 'challenge_logs', ['id'], unique=False)
    op.create_index(op.f('ix_challenge_logs_user_id'), 'challenge_logs', ['user_id'], unique=False)
    op.create_table('character_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('char_img_url', sa.String(length=500), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('graduated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_collections_id'), 'character_collections', ['id'], unique=False)
    op.create_index(op.f('ix_character_collections_user_id'), 'character_collections', ['user_id'], unique=False)
    op.create_table('character_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('leveled_up_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_history_character_id'), 'character_history', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_history_id'), 'character_history', ['id'], unique=False)
    op.create_index(op.f('ix_character_history_user_id'), 'character_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_history_user_id'), table_name='character_history')
    op.drop_index(op.f('ix_character_history_id'), table_name='character_history')
    op.drop_index(op.f('ix_character_history_character_id'), table_name='character_history')
    op.drop_table('character_history')
    op.drop_index(op.f('ix_character_collections_user_id'), table_name='character_collections')
    op.drop_index(op.f('ix_character_collections_id'), table_name='character_collections')
    op.drop_table('character_collections')
    op.drop_index(op.f('ix_challenge_logs_user_id'), table_name='challenge_logs')
    op.drop_index(op.f('ix_challenge_logs_id'), table_name='challenge_logs')
    op.drop_index(op.f('ix_challenge_logs_challenge_id'), table_name='challenge_logs')
    op.drop_table('challenge_logs')
    op.drop_index(op.f('ix_points_id'), table_name='points')
    op.drop_table('points')
    op.drop_index(op.f('ix_point_history_user_id'), table_name='point_history')
    op.drop_index(op.f('ix_point_history_id'), table_name='point_history')
    op.drop_table('point_history')
    op.drop_index(op.f('ix_health_records_user_id'), table_name='health_records')
    op.drop_index(op.f('ix_health_records_id'), table_name='health_records')
    op.drop_table('health_records')
    op.drop_index(op.f('ix_glucose_logs_user_id'), table_name='glucose_logs')
    op.drop_index(op.f('ix_glucose_logs_id'), table_name='glucose_logs')
    op.drop_table('glucose_logs')
    op.drop_index(op.f('ix_diet_logs_user_id'), table_name='diet_logs')
    op.drop_index(op.f('ix_diet_logs_id'), table_name='diet_logs')
    op.drop_table('diet_logs')
    op.drop_index(op.f('ix_diabetes_predictions_user_id'), table_name='diabetes_predictions')
    op.drop_index(op.f('ix_diabetes_predictions_id'), table_name='diabetes_predictions')
    op.drop_table('diabetes_predictions')
    op.drop_index(op.f('ix_characters_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_challenges_user_id'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_id'), table_name='challenges')
    op.drop_table('challenges')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
