"""refactor models with TimestampMixin

Revision ID: 5ab40f0c73ed
Revises: 21a72796b13e
Create Date: 2026-03-30 23:51:24.448943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ab40f0c73ed'
down_revision: Union[str, None] = '21a72796b13e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge_logs', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('character_collections', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('character_history', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('character_history', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('diabetes_predictions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('diet_logs', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('glucose_logs', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('health_records', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('point_history', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('points', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points', 'created_at')
    op.drop_column('point_history', 'updated_at')
    op.drop_column('health_records', 'updated_at')
    op.drop_column('glucose_logs', 'updated_at')
    op.drop_column('diet_logs', 'updated_at')
    op.drop_column('diabetes_predictions', 'updated_at')
    op.drop_column('character_history', 'updated_at')
    op.drop_column('character_history', 'created_at')
    op.drop_column('character_collections', 'updated_at')
    op.drop_column('challenge_logs', 'updated_at')
    # ### end Alembic commands ###
