"""add kakao_id to users

Revision ID: e0694784928e
Revises: c6788eb67cad
Create Date: 2026-04-15 21:44:28.065481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0694784928e'
down_revision: Union[str, None] = 'c6788eb67cad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kakao_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['kakao_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'kakao_id')
    # ### end Alembic commands ###
