name: ML CI

on:
  push:
    branches: [develop, main]
    paths:
      - "ml/**"
  pull_request:
    branches: [develop, main]
    paths:
      - "ml/**"

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
